// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ItemMaster struct {
	ItemID     string `json:"itemId"`
	ItemNumber string `json:"itemNumber"`
	ItemName   string `json:"itemName"`
}

type NewItemMaster struct {
	ItemNumber string `json:"itemNumber"`
	ItemName   string `json:"itemName"`
}
